syntax = "proto3";

package account;

option go_package = "./pb";

import "google/api/resource.proto";
import "google/api/annotations.proto";

// AccountService provides account management operations including retrieval and authentication.
service AccountService {
  // Standard CRUD operations
  // GetAccount retrieves an account by ID.
  rpc GetAccount (GetAccountRequest) returns (GetAccountReply) {}
  // ListAccounts retrieves a (paginated) list of all accounts for a user
  rpc ListAccounts (ListAccountsRequest) returns (ListAccountsReply) {
      option (google.api.http) = {
        get: "/v1/{parent=users/*}/accounts"
      };
  }

}

// Account represents a user's account information. Users may have multiple accounts.
message Account {
  option (google.api.resource) = {
      type: "rjfield.com/backend/Account"
      pattern: "users/{user_id}/accounts/{account_id}"
  };
  string name = 1; // Fully-qualified resource name in the format "users/{user_id}/accounts/{account_id}"

  string account_name = 3; // Descriptive name for the account
}

message GetAccountRequest {
  string account_id = 1;
}

message GetAccountReply {
    Account account = 1;
}

message ListAccountsRequest {
    string parent = 1 [(google.api.resource_reference) = {
      type: "rjfield.com/backend/User"
    }];  // The user resource name, e.g., "users/{user_id}"

    int32 page_size = 2;
    string page_token = 3;
}

message ListAccountsReply {
    repeated Account accounts = 1;
}