syntax="proto3";

package price;

option go_package = "./pb";

import "google/api/resource.proto";
import "google/api/annotations.proto";

// PriceService provides operations for retrieving and streaming price data.
service PriceService {
  // Standard CRUD operations
  // GetPrice retrieves a price by ID, typically a ticker symbol or product code.
  rpc GetPrice (GetPriceRequest) returns (GetPriceReply) {
    // Example:
    // GET {{host}}:{{port}}/v1/prices/MSFT
    option (google.api.http) = {
      get: "/v1/{name=prices/*}"
    };
  }

  // Batch operations
  rpc BatchGetPrices (BatchGetPricesRequest) returns (BatchGetPricesReply) {
    // Example:
    // GET {{host}}:{{port}}/v1/prices:batchGet?names=prices/AAPL&names=prices/GOOG&names=prices/MSFT
    option (google.api.http) = {
      get: "/v1/prices:batchGet"
    };
  }

  // Streaming operations
  rpc StreamPrices (StreamPricesRequest) returns (stream StreamPricesReply) {}

  // Custom operations
  // GetHistoricalPrices retrieves historical price data for a given asset.
  // Note that this is a very simple implementation that just returns 
  // the last 6 months of closing prices.
  // Additional flexibiltity could be added by allowing the client to specify a
  // date range and/or resolution (e.g., daily, weekly, monthly).
  rpc GetHistoricalPrices (GetHistoricalPricesRequest) returns (GetHistoricalPricesReply) {
    option (google.api.http) = {
      get: "/v1/{name=prices/*}:historical"
    };
  }
}

message GetPriceRequest {
  string name = 1 [(google.api.resource_reference) = {
    type: "rjfield.com/backend/Price"
  }]; // The price resource name, e.g., "prices/MSFT" 
}

message GetPriceReply {
  Price price = 1;
}

message BatchGetPricesRequest {
  repeated string names = 1 [(google.api.resource_reference) = {
    type: "rjfield.com/backend/Price"
  }]; // The price resource names, e.g., "prices/MSFT", "prices/AAPL", "prices/GOOG"
} 
message BatchGetPricesReply {
  repeated Price prices = 1;
}

message StreamPricesRequest {
  repeated string names = 1;
}

message StreamPricesReply {
  Price price = 1;
}

message GetHistoricalPricesRequest {
  string name = 1 [(google.api.resource_reference) = {
    type: "rjfield.com/backend/Price"
  }]; // The price resource name, e.g., "prices/MSFT" 
}

message GetHistoricalPricesReply {
  repeated Price prices = 1;
}

// Price is a top level message representing an asset price
message Price {
    option (google.api.resource) = {
        type: "rjfield.com/backend/Price"
        pattern: "prices/{price_id}"
    };
  string name = 10; // fully qualified name, e.g. "prices/456"

  double price = 2;
  double price_change = 3;
}