syntax="proto3";

package price;

option go_package = "./pb";

// PriceService provides operations for retrieving and streaming price data.
service PriceService {
  // Standard CRUD operations
  // GetPrice retrieves a price by ID, typically a ticker symbol or product code.
  rpc GetPrice (GetPriceRequest) returns (GetPriceReply) {}
  // GetPrices retrieves multiple prices by their IDs.
  rpc GetPrices (GetPricesRequest) returns (GetPricesReply) {}

  // Streaming operations
  rpc StreamPrices (StreamPricesRequest) returns (stream StreamPricesReply) {}
}

message GetPriceRequest {
  string price_id = 1;
}

message GetPriceReply {
  Price price = 1;
}

message GetPricesRequest {
  repeated string price_ids = 1;
} 

message GetPricesReply {
  repeated Price prices = 1;
} 

message StreamPricesRequest {
  repeated string price_ids = 1;
}

message StreamPricesReply {
  Price price = 1;
}

// Price is a top level message representing an asset price
message Price {
  string price_id = 1;
  double price = 2;
  double price_change = 3;
}