syntax = "proto3";

package user;

option go_package = "./pb";

import "google/api/resource.proto";
import "google/api/annotations.proto";

// UserService provides user management operations including CRUD operations and authentication.
service UserService {
    // Standard CRUD operations
    // CreateUser creates a new user.
    rpc CreateUser (CreateUserRequest) returns (CreateUserReply) {}
    // ListUsers retrieves a (paginated) list of all users.
    rpc ListUsers (ListUsersRequest) returns (ListUsersReply) {
        option (google.api.http) = {
          get: "/v1/users"
        };
    }
    // GetUser retrieves a user by ID.
    rpc GetUser (GetUserRequest) returns (GetUserReply) {
        // Example: GET {{host}}:{{port}}/v1/users/123
        option (google.api.http) = {
          get: "/v1/{name=users/*}"
        };
    }
    // UpdateUser updates an existing user.
    rpc UpdateUser (UpdateUserRequest) returns (UpdateUserReply) {}
    // DeleteUser deletes a user by ID.
    rpc DeleteUser (DeleteUserRequest) returns (DeleteUserReply) {}

    // Additional operations
    // AuthenticateUser authenticates a user with username and password.
    // Note that AuthenticateUser() is for demonstration purposed only. 
    // Basic Auth is not recommended for production systems. Use OAuth2 or JWT instead.
    // Note that the HTTP annotation indicates a POST request as
    // recommended for all custom methods in the Google AIP.
    rpc AuthenticateUser (AuthenticateUserRequest) returns (AuthenticateUserReply) {
        option (google.api.http) = {
          post: "/v1/users:authenticate"
          body: "*"
        };
    }
}

// User is a top level message representing a user in the system.
message User {
    option (google.api.resource) = {
        type: "rjfield.com/backend/User"
        pattern: "users/{user_id}"
    };
    string name = 1; // Fully-qualified resource name in the format "users/{user_id}"

    string username = 3; // Unique username for login
    string password_hash = 4; // Hashed password for authentication
    string token = 5; // Authentication token for session management
    string given_name = 6; // User's first name
    string family_name = 7; // User's last name
    string email = 8; // User's email address
}

message CreateUserRequest {
    User user = 1;
}

message CreateUserReply {
    User user = 1;
}

message GetUserRequest {
    string name = 1 [(google.api.resource_reference) = {
        type: "rjfield.com/backend/User"
    }];
}

message GetUserReply {
    User user = 1;
}

message UpdateUserRequest {
    User user = 1;
}   

message UpdateUserReply {
    User user = 1;
}   

message DeleteUserRequest {
    string name = 1 [(google.api.resource_reference) = {
        type: "rjfield.com/backend/User"
    }];
}

message DeleteUserReply {
    bool success = 1;
}

message ListUsersRequest {
    int32 page_size = 1;
    string page_token = 2;
}
message ListUsersReply {
    repeated User users = 1;
    string next_page_token = 2;
}

message AuthenticateUserRequest {
  string username = 1;
  string password = 2;
}
message AuthenticateUserReply {
  string token = 1;
  string name = 2;
}
